apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-secret
type: Opaque
data:
  ROOT_PASSWORD: dGVzdA==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
spec:
  replicas: 2
  secretName: mysql-cluster-secret